# Generated by Django 4.1.7 on 2023-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycrud',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companycrud',
            name='last_udpated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
