# Generated by Django 4.1.7 on 2023-04-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companycrud_is_active_companycrud_last_udpated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycrud',
            name='last_udpated_on',
        ),
    ]
