# Generated by Django 4.1.7 on 2023-04-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_companymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyModel',
        ),
    ]
